spring.application.name=Dapp.Jaggery.Supplychain

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Blockchain Node URL (Ganache)
blockchain.nodeUrl=http://localhost:7545

# Contract Address (deployed to Ganache)
blockchain.contractAddress=0x44288A29B2e628687b1570b684D89Ee15c0DAA11

# Private Key (from Ganache)
blockchain.producer.privateKey = 0x83e66f02d5406c7b5fc7c03e8b994dc065186f6d69feb8055ee537ef8b2a3669
blockchain.fssai1.privateKey = 0xed41eac5a5091cbf36bc5d7c58570d3fccdabdf8cd3ae5fa39f2e118a287edf0
blockchain.fssai2.privateKey = 0x82b0c245db1d644d728f68c828447f2cc6ae6e583203c73bd860bf2f0566d4b9
blockchain.distributor.privateKey = 0x7b60dd3c2119c66922aed39197064c67b35cac226ff571598f292d0bbf871f3a
